	__CONFIG _CP_OFF&_WDT_OFF&_PWRTE_ON&_LVP_OFF&_MCLRE_OFF&_INTOSC_OSC_CLKOUT
	LIST	  P=16F628A		
	INCLUDE  <P16F628A.INC>
	CBLOCK  0x20
	ENDC
	ORG	0
Inicio
	call	LCD_Inicializa
	movlw	Mensaje0
	call	LCD_Mensaje
	sleep
Mensajes
	addwf	PCL,F
Mensaje0
	DT "Hola!, que tal?   ", 0x00	
	;INCLUDE  <LCD_4BIT.INC>
	;INCLUDE  <LCD_MENS.INC>
	;INCLUDE  <RETARDOS.INC>
	INCLUDE  "T:\SISTEMAS PROGRAMABLES\Programas\LCD_4BIT.INC"
	INCLUDE  "T:\SISTEMAS PROGRAMABLES\Programas\LCD_MENS.INC"
	INCLUDE  "T:\SISTEMAS PROGRAMABLES\Programas\RETARDOS.INC"
	END